### ISSUE TITLE
Target URI hasn't been generated for 'rest_client.g.dart';

### ISSUE THREAD

**Issue by abhi-cureore** [rrifafauzikomara/MovieApp#2]
Hi @abhi-cureore

First you need to move to core module using cd command. For ex: cd core.

The you need to run this.
flutter pub run build_runner build

I have tried your solution but not worked still have the same issue
attaching what i get after running the command
https://www.dropbox.com/s/afe4zlpc5ubzas9/issue2.PNG?dl=0

**Comment by abhi-cureore** [comment]
Remove dependency_overrides: analyzer: 0.39.14 entirely solves my problem

**Comment by rrifafauzikomara** [comment]
This because you don't use the latest version of Flutter. So you need to remove `analyzer`.
