### ISSUE TITLE
 Gradle build failed to produce an .apk file. It's likely that this file was generated under D:\Flutter\Bloc Pattern Api Call\MovieApp-master\build, but the tool couldn't find it.

### ISSUE THREAD

**Issue by abhi-cureore** [rrifafauzikomara/MovieApp#3]
Every time i try to build apk file

**Comment by rrifafauzikomara** [comment]
Hi @abhi-cureore 

Please provide full of the error message. And also the result of `flutter doctor -v`

**Comment by abhi-cureore** [comment]
D:\Softwares\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.20.4 at D:\Softwares\flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Cureore\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Redmi Note 5 Pro (mobile) • 7f8cdc40 • android-arm64 • Android 7.1.1 (API 25)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by abhi-cureore** [comment]
Issue resolved after adding flavor  to development in edit configuration
